### ISSUE TITLE
关于Error: Timeout for packet id 1的问题

### ISSUE THREAD

**Issue by ZyphrZero** [KirosHan/Palworld-server-protector-electron#2]
因为rcon里有id验证，以python为例，只要把这部分代码用补丁的方式注释掉就可以了
![image](https://github.com/KirosHan/Palworld-server-protector-electron/assets/133507172/f568ae48-02da-423e-9685-9d9639a32696)

**Comment by KirosHan** [comment]
感谢，
了解原因了🙇

**Comment by KirosHan** [comment]
请问知道这个服务端是什么编码吗，ascii和utf8都没法发送中文

**Comment by ZyphrZero** [comment]
> 请问知道这个服务端是什么编码吗，ascii和utf8都没法发送中文

是什么编码我也不清楚呢，只有等官方那边做处理了
